# Generated by Django 3.1.5 on 2021-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_url', models.CharField(blank=True, max_length=100, null=True)),
                ('img_url', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'movie_db',
                'managed': False,
            },
        ),
    ]
